# Generated by Django 2.2 on 2020-03-26 19:50

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(db_index=True, max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Аудиторія',
                'verbose_name_plural': 'Аудиторії',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(db_index=True, max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Групи',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_index=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachers_name', models.CharField(db_index=True, max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Вчитель',
                'verbose_name_plural': 'Вчителя',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('beginning', models.TimeField()),
                ('ending', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('1', 'Понеділок'), ('2', 'Вівторок'), ('3', 'Середа'), ('4', 'Четверг'), ('5', "П'ятниця")], max_length=200)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.Classroom')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.Groups')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.Subject')),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.Teachers')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.Time')),
            ],
            options={
                'verbose_name': 'Заняття',
                'verbose_name_plural': 'Розклад',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
