# Generated by Django 2.2 on 2020-03-27 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='classroom',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Аудиторія'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='group_name',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Група'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.Classroom', verbose_name='Аудиторія'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.Groups', verbose_name='Група'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.Subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teachers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.Teachers', verbose_name='Вчитель'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.Time', verbose_name='Пара'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='weekday',
            field=models.CharField(choices=[('1', 'Понеділок'), ('2', 'Вівторок'), ('3', 'Середа'), ('4', 'Четверг'), ('5', "П'ятниця")], max_length=200, verbose_name='День тижня'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='teachers_name',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Вчитель'),
        ),
    ]
